<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Channel extends Model
{
    use HasFactory;


    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function($item){
            $item->slug=Str::slug($item->name);
        });
    }
    public function threads(){
        return $this->hasMany(Thread::class);
    }



}
