<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Thread extends Model
{
    use HasFactory;
    protected $guarded=[];
    public function replies(){
        return $this->hasMany(Reply::class);
    }

    // create slug for any thread
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function ($thread){
            $thread->slug=Str::slug($thread->title);
        });
    }
}

